package org.apache.dolphinscheduler.common.serializer;

import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.ser.std.UUIDSerializer;
import com.xxdb.data.*;
import com.xxdb.data.Void;

public class SerializerModule {
    public static SimpleModule getModule() {
        return new SimpleModule()
                .addSerializer(BasicAnyVector.class, new AnyVectorSerializer())
                .addSerializer(BasicArrayVector.class, new ArrayVectorSerializer())
                .addSerializer(BasicBooleanMatrix.class, new BooleanMatrixSerializer())
                .addSerializer(BasicBoolean.class, new BooleanSerializer())
                .addSerializer(BasicBooleanVector.class, new BooleanVectorSerializer())
                .addSerializer(BasicByteMatrix.class, new ByteMatrixSerializer())
                .addSerializer(BasicByte.class,new ByteSerializer())
                .addSerializer(BasicByteVector.class,new ByteVectorSerializer())
                .addSerializer(BasicChart.class,new ChartSerializer())
                .addSerializer(BasicChunkMeta.class,new ChunkMetaSerializer())
                .addSerializer(BasicComplex.class,new ComplexSerializer())
                .addSerializer(BasicComplexMatrix.class,new ComplexMatrixSerializer())
                .addSerializer(BasicComplexVector.class,new ComplexVectorSerializer())
                .addSerializer(BasicDate.class,new DateSerializer())
                .addSerializer(BasicDateMatrix.class,new DateMatrixSerializer())
                .addSerializer(BasicDateVector.class,new DateVectorSerializer())
                .addSerializer(BasicDateTime.class,new DateTimeSerializer())
                .addSerializer(BasicDateTimeMatrix.class,new DateTimeMatrixSerializer())
                .addSerializer(BasicDateTimeVector.class,new DateTimeVectorSerializer())
                .addSerializer(BasicDateHour.class,new DateHourSerializer())
                .addSerializer(BasicDateHourMatrix.class,new DateHourMatrixSerializer())
                .addSerializer(BasicDateHourVector.class,new DateHourVectorSerializer())
                .addSerializer(BasicDecimal32.class,new Decimal32Serializer())
                .addSerializer(BasicDecimal32Vector.class,new Decimal32VectorSerializer())
                .addSerializer(BasicDecimal64.class,new Decimal64Serializer())
                .addSerializer(BasicDecimal64Vector.class,new Decimal64VectorSerializer())
                .addSerializer(BasicDecimal128.class,new Decimal128Serializer())
                .addSerializer(BasicDecimal128Vector.class,new Decimal128VectorSerializer())
                .addSerializer(BasicDictionary.class,new DictionarySerializer())
                .addSerializer(BasicDouble.class,new DoubleSerializer())
                .addSerializer(BasicDoubleMatrix.class,new DoubleMatrixSerializer())
                .addSerializer(BasicDoubleVector.class,new DoubleVectorSerializer())
                .addSerializer(BasicDuration.class,new DurationSerializer())
                .addSerializer(BasicDurationVector.class,new DurationVectorSerializer())
                .addSerializer(BasicFloat.class,new FloatSerializer())
                .addSerializer(BasicFloatMatrix.class,new FloatMatrixSerializer())
                .addSerializer(BasicFloatVector.class,new FloatVectorSerializer())
                .addSerializer(BasicInt.class,new IntSerializer())
                .addSerializer(BasicIntMatrix.class,new IntMatrixSerializer())
                .addSerializer(BasicIntVector.class,new IntVectorSerializer())
                .addSerializer(BasicInt128.class,new Int128Serializer())
                .addSerializer(BasicInt128Vector.class,new Int128VectorSerializer())
                .addSerializer(BasicIPAddr.class,new IPAddrSerializer())
                .addSerializer(BasicIPAddrVector.class,new IPAddrVectorSerializer())
                .addSerializer(BasicLong.class,new LongSerializer())
                .addSerializer(BasicLongMatrix.class,new LongMatrixSerializer())
                .addSerializer(BasicLongVector.class,new LongVectorSerializer())
                .addSerializer(BasicMinute.class,new MinuteSerializer())
                .addSerializer(BasicMinuteVector.class,new MinuteVectorSerializer())
                .addSerializer(BasicMinuteMatrix.class,new MinuteMatrixSerializer())
                .addSerializer(BasicMonth.class,new MonthSerializer())
                .addSerializer(BasicMonthVector.class,new MonthVectorSerializer())
                .addSerializer(BasicMonthMatrix.class,new MonthMatrixSerializer())
                .addSerializer(BasicNanoTime.class,new NanoTimeSerializer())
                .addSerializer(BasicNanoTimeVector.class,new NanoTimeVectorSerializer())
                .addSerializer(BasicNanoTimeMatrix.class,new NanoTimeMatrixSerializer())
                .addSerializer(BasicNanoTimestamp.class,new NanoTimestampSerializer())
                .addSerializer(BasicNanoTimestampVector.class,new NanoTimestampVectorSerializer())
                .addSerializer(BasicNanoTimestampMatrix.class,new NanoTimestampMatrixSerializer())
                .addSerializer(BasicPoint.class,new PointSerializer())
                .addSerializer(BasicPointVector.class,new PointVectorSerializer())
                .addSerializer(BasicSecond.class,new SecondSerializer())
                .addSerializer(BasicSecondVector.class,new SecondVectorSerializer())
                .addSerializer(BasicSecondMatrix.class,new SecondMatrixSerializer())
                .addSerializer(BasicSet.class,new SetSerializer())
                .addSerializer(BasicShort.class,new ShortSerializer())
                .addSerializer(BasicShortMatrix.class,new ShortMatrixSerializer())
                .addSerializer(BasicShortVector.class,new ShortVectorSerializer())
                .addSerializer(BasicString.class,new StringSerializer())
                .addSerializer(BasicStringVector.class,new StringVectorSerializer())
                .addSerializer(BasicStringMatrix.class,new StringMatrixSerializer())
                .addSerializer(BasicSymbolVector.class,new SymbolVectorSerializer())
                .addSerializer(BasicTable.class,new TableSerializer())
                .addSerializer(BasicTableSchema.class,new TableSchemaSerializer())
                .addSerializer(BasicTime.class,new TimeSerializer())
                .addSerializer(BasicTimeVector.class,new TimeVectorSerializer())
                .addSerializer(BasicTimeMatrix.class,new TimeMatrixSerializer())
                .addSerializer(BasicTimestamp.class,new TimestampSerializer())
                .addSerializer(BasicTimestampVector.class,new TimestampVectorSerializer())
                .addSerializer(BasicTimestampMatrix.class,new TimestampMatrixSerializer())
                .addSerializer(BasicUuid.class,new UuidSerializer())
                .addSerializer(BasicUuidVector.class,new UuidVectorSerializer())
                .addSerializer(BasicVoidVector.class,new VoidVectorSerializer())
                .addSerializer(Void.class,new VoidSerializer());
    }
}
